import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

import "./globals.css";

import Footer from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CheckStarterPage = dynamic(
    () => import("@/components/etc/check-start"),
    {
      ssr: false,
    }
  );
  const CheckLogin = dynamic(() => import("@/components/etc/check-login"), {
    ssr: false,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-[430px] mx-auto w-full min-h-full bg-[#0e0a5f] z-10 relative flex flex-col">
          {children}
          <CheckStarterPage />
          <CheckLogin />
          <Footer />
        </main>
      </body>
    </html>
  );
}
